export const ACTION_ADD_REQUEST = "ACTION_ADD_REQUEST";
export const ACTION_ADD_SUCCESS = "ACTION_ADD_SUCCESS";
export const ACTION_ADD_FAIL = "ACTION_ADD_FAIL";
export const ACTION_LIST_REQUEST = "ACTION_LIST_REQUEST";
export const ACTION_LIST_SUCCESS = "ACTION_LIST_SUCCESS";
export const ACTION_LIST_FAIL = "ACTION_LIST_FAIL";
