export const CHALLENGE_LIST_REQUEST = "CHALLENGE_LIST_REQUEST";
export const CHALLENGE_LIST_SUCCESS = "CHALLENGE_LIST_SUCCESS";
export const CHALLENGE_LIST_FAIL = "CHALLENGE_LIST_FAIL";
export const CHALLENGE_CREATE_REQUEST = "CHALLENGE_CREATE_REQUEST";
export const CHALLENGE_CREATE_SUCCESS = "CHALLENGE_CREATE_SUCCESS";
export const CHALLENGE_CREATE_FAIL = "CHALLENGE_CREATE_FAIL";
