// src/constants/initiativeConstants.js
export const INITIATIVE_LIST_REQUEST = "INITIATIVE_LIST_REQUEST";
export const INITIATIVE_LIST_SUCCESS = "INITIATIVE_LIST_SUCCESS";
export const INITIATIVE_LIST_FAIL = "INITIATIVE_LIST_FAIL";

export const INITIATIVE_DETAILS_REQUEST = "INITIATIVE_DETAILS_REQUEST";
export const INITIATIVE_DETAILS_SUCCESS = "INITIATIVE_DETAILS_SUCCESS";
export const INITIATIVE_DETAILS_FAIL = "INITIATIVE_DETAILS_FAIL";

export const INITIATIVE_CREATE_REQUEST = "INITIATIVE_CREATE_REQUEST";
export const INITIATIVE_CREATE_SUCCESS = "INITIATIVE_CREATE_SUCCESS";
export const INITIATIVE_CREATE_FAIL = "INITIATIVE_CREATE_FAIL";

export const INITIATIVE_JOIN_REQUEST = "NITIATIVE_JOIN_REQUEST";
export const INITIATIVE_JOIN_SUCCESS = "INITIATIVE_JOIN_SUCCESS";
export const INITIATIVE_JOIN_FAIL = "INITIATIVE_JOIN_FAIL";
